### ISSUE TITLE
how to use this script with proxies?

### ISSUE THREAD

**Issue by Zakirzhan** [chrispetrou/youtube2mp3#1]
I have a proxy list in "proxy.txt"
Can I download each YouTube video using a random proxy in the IP proxy list

I want do to like this
./youtube2mp3.py -f files.txt -t 10 -x proxies.txt

**Comment by chrispetrou** [comment]
Hi @Zakirzhan ! Sorry for my late response. At the moment the script does not support a proxy/proxy-list but this could be and might added in the future.
